# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

UPPER_LIMIT = 4E6

buffer_array = [1,2]
sum = 0

while buffer_array[1] < UPPER_LIMIT
  sum += buffer_array[1] if buffer_array[1]%2 == 0
  buffer_array = buffer_array[1], buffer_array[0] + buffer_array[1]
end

puts sum